### ISSUE TITLE
Does the editor work on Linux?

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [AdAstra-LD/DS-Pokemon-Rom-Editor#19]

**Comment by AdAstra-LD** [comment]
It's a Windows application, so... not natively.

**Comment by JakobDev** [comment]
.NET Apps also works on Linux. The Problem here is, that the used GUI Framework WPF doesn't work on Linux. So if you want to port to another Framework sometime in the future you should use a framework that is cross platform.
