### ISSUE TITLE
Incorrect DVs for trainers in HGSS

### ISSUE THREAD

**Issue by OtakuGracie** [AdAstra-LD/DS-Pokemon-Rom-Editor#20]
The DV displayed for a number of trainers' pokemon in HGSS is incorrect. Examples include all elite four members, leader claire, and a number of others. For those it displays incorrectly they seem to be off by 8192. My guess is that the value read in for a trainer's pokemon's DV also holds a different value that is simply set to 0 for many pokemon in the trainer files. This issue seems to be specific to HGSS from my testing.

![DSPRE_HGSS_DV_Error](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/73315709/b8cf9296-93b9-4045-ae9f-c087d573d072)

**Comment by AdAstra-LD** [comment]
As much as I agree with your intuition, without knowing the effect that 8192 has on the DV number, it's hard for me to imagine a more correct way to display that value. 
It may be a bit flag on bit #13, it may be part of a wider bitfield... 
At the moment, I don't know.
