### ISSUE TITLE
Exception opening trainer files in Diamond and Pearl

### ISSUE THREAD

**Issue by OtakuGracie** [AdAstra-LD/DS-Pokemon-Rom-Editor#21]
Attempting to view a trainer with more than one Pokemon in the trainer editor with Diamond and Pearl causes an exception that crashes the trainer editor. From my screenshot you can see that it seems to load the first Pokemon in a party fine.

![DSPRE_DP_trainerEditor_Error](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/73315709/57e1ce9e-1f4e-4913-b711-cbc2370c9b71)

**Comment by OtakuGracie** [comment]
Trainer class sprites also seem to not be loading in the editor for Diamond and Pearl

**Comment by OtakuGracie** [comment]
closed by accident

**Comment by Mixone-FinallyHere** [comment]
@OtakuGracie im gona give it a go to fix can you share some more details here or on the discord?

- Does this happen every single time no matter what language or game version or is it a specific one?
- Can you share the full error log in text format or a more complete one?
- Did you modify the rom in anyway or does this happen with raw games?
