### ISSUE TITLE
[Bug] Manually changing event in event editor does not load map

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [AdAstra-LD/DS-Pokemon-Rom-Editor#31]
Likely event handler is missing loading of textures and map since events do appear

**Comment by Mixone-FinallyHere** [comment]
Fixed


https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/11949750/615e093f-0892-4e41-b0f5-070335e39439

**Comment by AdAstra-LD** [comment]
This was an actual design choice, not a bug... But it can work too

**Comment by AdAstra-LD** [comment]
This was an actual design choice, not a bug... But it can work too
