### ISSUE TITLE
Personal Data Editor loads data incorrectly for Pokemon

### ISSUE THREAD

**Issue by OttoTonsorialist** [AdAstra-LD/DS-Pokemon-Rom-Editor#36]
There are two issues with the way pokemon data is getting loaded in the Personal Data Editor window:

- There seem to be 2 extra bytes in between the colorAndFlip byte, and the start of the TM/HM bytes. I don't know what these 2 extra bytes are for, but you can easily see by this by looking at the values for a given pokemon. For example, Shaymin's first 4 TMs according to bulbapedia are 6, 9, 10, 11. The page currently reports 22, 25, 26, 27.
- The growth rate lookup is incorrect. You need to be using the values: 0=MediumFast, 1=Erratic, 2=Fluctuating, 3=MediumSlow, 4=Fast, 5=Slow

**Comment by AdAstra-LD** [comment]
Thanks for pointing this out, will fix asap.

As for #1, they're just alignment/padding bytes. No use at all.

**Comment by AdAstra-LD** [comment]
I also verified problem ##2, gotta change the labels now
