### ISSUE TITLE
Undocumented DPPT encounter fields

### ISSUE THREAD

**Issue by SunakazeKun** [AdAstra-LD/DS-Pokemon-Rom-Editor#37]
Greetings, I noticed the editor for DPPT wild encounters is incomplete. From further research, I found out what these remaining fields correspond to:
0x8C int Shellos East Sea chance (0 to 100)
0x90 int Gastrodon East Sea chance (0 to 100)
0x94 int Unused
0x98 int Unused
0x9C int Unused
0xA0 int Unown table (0 to 9, apparently)

The range 0xF8 to 0x123 is reserved for rock smash encounters, apparently. But I never tested if this works...

Implementing the above fields is necessary because currently, East Sea form and Unown fields get saved as 0, thus making those forms unobtainable.

**Comment by AdAstra-LD** [comment]
Hi! Quick question... how did you know that "range 0xF8 to 0x123 is reserved for rock smash encounters" without testing if it works?

**Comment by SunakazeKun** [comment]
Nevermind, it was dummied-out. However, according to leaked information, it was intended for rock smash encounters. In the end, these values do nothing.
