### ISSUE TITLE
Personal Data Editor doesn't save/load TM/HMs correctly

### ISSUE THREAD

**Issue by PoundCat** [AdAstra-LD/DS-Pokemon-Rom-Editor#43]
Basically, I will change a Pokemon's TMs and if i go to another another pokemon then go back, all the TM/HMs will be +1  of what they were when I saved it. 

I think ive narrowed it down to how the tool "loads" the TM/HM list because i tried this on a fresh ROM and all the TM/HMs were already +1 to what they shouldve been (According to bulbapedia)

I was using a Platinum ROM when i discovered this

**Comment by AdAstra-LD** [comment]
Known issue. it's been fixed (17f905ad34addefeeee3c4e835992b4f92566d56).
I haven't released an update for it yet.
