### ISSUE TITLE
SetDeoxysForm uses too many arguments

### ISSUE THREAD

**Issue by SunakazeKun** [AdAstra-LD/DS-Pokemon-Rom-Editor#44]
The SetDeoxysForm script command is incorrectly parsed. For example, it currently looks like it takes four arguments:
``SetDeoxysForm 0 76 386 0``
However, it only uses the first argument (the form to change into). The other three values correspond to another script command, ``PlayCry`` in this particular case.

**Comment by AdAstra-LD** [comment]
It's correctly documented on the public sheet but was wrong in DSPRE's internal database, for some reason. Good catch, thanks.

**Comment by AdAstra-LD** [comment]
It was correctly documented on the public sheet but not in DSPRE's internal database, for some reason. Nice catch, thanks.
