### ISSUE TITLE
[Bug] ReplaceMove script command arguments missing

### ISSUE THREAD

**Issue by SunakazeKun** [AdAstra-LD/DS-Pokemon-Rom-Editor#54]
The three arguments for the `ReplaceMove` script command in DPPT are missing, rendering the command unusable. According to the app's command database, it takes no arguments, which is wrong. However, it has three arguments:

1. Party Pokémon index
2. Move slot index
3. Move ID

**Comment by AdAstra-LD** [comment]
Source of this information is the public scrcmd doc, I assume?

> * Party Pokémon index
> * Move slot index
> * Move ID

**Comment by AdAstra-LD** [comment]
Yeah, nevermind. Whatever it was, the ASM code seems to confirm the documented behavior.

Thanks for this. I'm sure there are more like this one
