### ISSUE TITLE
Wrong line numbers in the script editor's error messages

### ISSUE THREAD

**Issue by soup244** [AdAstra-LD/DS-Pokemon-Rom-Editor#8]
When there is a bug in my script, the editor spits out wrong line numbers in the error message, making debugging really hard. idk, if i'm doing something wrong or what, but its hard to program like this.
![Screenshot 2022-06-06 190417](https://user-images.githubusercontent.com/61199294/172269005-631294d4-3595-4fcb-8981-a8eb26163eec.png)

Thanks,
Soup

**Comment by AdAstra-LD** [comment]
That's probably due to 3 blank lines being ignored by DSPRE and messing up with the numbering. 
I can't guarantee a fix will be out soon, since I don't really plan on maintaining DSPRE for much longer.

Thanks for notifying me, though.

**Comment by AdAstra-LD** [comment]
Nevermind, it's fixed. 
![image](https://user-images.githubusercontent.com/76622070/173186942-4af35ec8-a88e-40f2-b1e1-9f9130c57ed7.png)
